import { ExternalLink, LinkIcon } from "lucide-react";

import AIComponentButton from "./AIComponentButton";
import AIComponentEntry from "./AIComponentEntry";
import AIComponentHeader from "./AIComponentHeader";

import { Card, CardContent } from "../components/ui/card";

export type PurchaseLinkProps = {
  registrationNumber?: string;
  insuranceLabel: string;
  vehicleType: string;
  coverage: "comprehensive" | "third-party";
  url: string; //url to the purchase page
};

const AIPurchaseLinkComponent = (purchaseLink: PurchaseLinkProps) => {
  return (
    <Card className="w-full">
      <CardContent className="p-4">
        {/* Header */}
        <AIComponentHeader
          Icon={LinkIcon}
          title="Insurance Purchase"
          subtitle="Your insurance details are ready"
        />

        {/* Purchase details */}
        <div className="bg-muted/50 rounded-md p-3 mb-3">
          <AIComponentEntry
            title="Registration"
            content={purchaseLink.registrationNumber || "Not set"}
          />
          <AIComponentEntry title="Vehicle" content={purchaseLink.vehicleType} />
          <AIComponentEntry
            title="Cover Type"
            content={
              purchaseLink.coverage === "comprehensive"
                ? "Comprehensive"
                : "Third Party"
            }
          />
        </div>

        {/* Action button */}
        <AIComponentButton
          Icon={ExternalLink}
          text="Continue to Purchase"
          link={purchaseLink.url}
        />

        {/* Info */}
        <p className="text-xs text-muted-foreground mt-2 text-center">
          This is a prefilled purchase link generated by the AI.
        </p>
      </CardContent>
    </Card>
  );
};

export default AIPurchaseLinkComponent;
